E11. Workshop/Web/Blog.Web/Controllers/ApplicationUserController.cs
//using Blog.Infrastructure.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
//using Blog.Core.Models.User;

namespace Blog.Controllers
{
    using System.Text;
    using System.Threading.Tasks;
    using Services.Data;
    using Web.ViewModels.ApplicationUser;

    //[Authorize]
    public class ApplicationUserController : Controller
    {
        private readonly IApplicationUserService userService;

        public ApplicationUserController(IApplicationUserService userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        //[AllowAnonymous]
        public IActionResult Register()
        {
            return this.View(new RegisterUserInputModel());
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            bool usernameOrEmailTaken = await this.userService.UsernameExistsAsync(model.Username) ||
                                        await this.userService.EmailExistsAsync(model.Email);
            if (usernameOrEmailTaken)
            {
                return this.RedirectToAction("Login");
            }

            if (model.Password != model.PasswordConfirmation)
            {
                return this.View(model);
            }

            await this.userService.CreateUserAsync(model);

            return this.RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginInputModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string userId = await this.userService.GetIdByUsernameAsync(model.Username);
            if (userId == null)
            {
                ModelState.AddModelError("Username", "Invalid username!");
                return this.View(model);
            }

            bool isLoggedIn = 
                await this.userService.ValidateLoginInfoAsync(model);
            if (!isLoggedIn)
            {
                ModelState.AddModelError("Password", "Invalid password!");
                return this.View(model);
            }

            HttpContext.Session.Set("userId", Encoding.UTF8.GetBytes(userId));

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

E11. Workshop/Web/Blog.Web/Controllers/ArticleController.cs
namespace Blog.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;

    using Services.Data;
    using ViewModels.Article;
    using ViewModels.Genres;

    public class ArticleController : Controller
    {
        private readonly IGenreService genreService;

        public ArticleController(IGenreService genreService)
        {
            this.genreService = genreService;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            ICollection<ListGenreArticleAddViewModel> genres =
                await this.genreService.GetAllAsync();
            ArticleAddViewModel vm = new ArticleAddViewModel()
            {
                Genres = genres,
            };

            return View(vm);
        }
    }
}

E11. Workshop/Web/Blog.Web/Controllers/BaseController.cs
namespace Blog.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

E11. Workshop/Web/Blog.Web/Controllers/HomeController.cs
namespace Blog.Web.Controllers
{
    using System.Diagnostics;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels;

    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

E11. Workshop/Web/Blog.Web/Views/ApplicationUser/Login.cshtml
@model Blog.Web.ViewModels.ApplicationUser.LoginInputModel
@{
    ViewData["Title"] = "Log in";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<div class="row">
    <div class="col-md-4 offset-md-4">
        <section>
            <form id="account" method="post">
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="text-center mb-3">
                    <label asp-for="@Model.Username" class="form-label"></label>
                    <input asp-for="@Model.Username" class="form-control" autocomplete="username" aria-required="true" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>
                <div class="text-center mb-3">
                    <label asp-for="@Model.Password" class="form-label"></label>
                    <input asp-for="@Model.Password" type="password" class="form-control" autocomplete="current-password" aria-required="true" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="text-center">
                    <button id="login-submit" type="submit" class="btn btn-primary">Log in</button>
                </div>
            </form>
        </section>
    </div>
</div>

E11. Workshop/Web/Blog.Web/Views/ApplicationUser/Register.cshtml
@model Blog.Web.ViewModels.ApplicationUser.RegisterUserInputModel
@{
    ViewData["Title"] = "Register";
}

<h1 class="text-center">@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form id="registerForm" method="post">
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Username">Username</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Username" />
                <span asp-validation-for="@Model.Username" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Email">Email</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Email" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Password">Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.Password" />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.PasswordConfirmation">Confirm Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.PasswordConfirmation" />
                <span asp-validation-for="@Model.PasswordConfirmation" class="text-danger"></span>
            </div>
            <div class="text-center">
                <button id="registerSubmit" type="submit" class="btn btn-primary">Register</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

E11. Workshop/Web/Blog.Web/Views/Article/Add.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Blog.Web.ViewModels.Article.ArticleAddViewModel;

@{
    ViewBag.Title = "Create a New Article";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control" aria-required="true" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Content" class="form-label">Content</label>
                <input asp-for="Content" class="form-control" aria-required="true" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.GenreId" class="form-label">Genre</label>
                <select asp-for="@Model.GenreId" class="form-control">
                    @foreach (var genre in Model.Genres)
                    {
                        <option value="@genre.Id">@genre.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.GenreId" class="text-danger"></span>
            </div>
            <div class="mb-3 text-center">
                <input class="btn btn-primary" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

E11. Workshop/Web/Blog.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="mt-4 p-5 bg-primary text-white rounded">
        <h1>The Best Blog</h1>
        <p>Welcome to the best blog ever!</p>
    </div>
</div>

E11. Workshop/Web/Blog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="All">All Articles</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Add">Write a New Article</a>
                       </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Blog
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>